service:
  url: "https://abrechnung.example.lol"
  name: "SFT Kybernetik-Abrechnung 2.5a"

database:
  host: null
  user: "abrechnung"
  password: "Mb2.r5oHf-0t"
  dbname: "abrechnung"

api:
  secret_key: "verysecretsecret"
  host: "localhost"
  port: 8080
  id: default

email:
  address: "abrechnung@example.lol"
  host: "localhost"
  port: 587
  mode: "smtp-starttls"
  auth:
    "username": "abrechnung"
    "password": "Mb2.r5oHf-0t"
