services:
  api:
    command: api
    env_file: .env
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--connect-timeout", "10", "--silent", "http://127.0.0.1:8080/"]

  mailer:
    extends:
      service: api
    command: mailer
    healthcheck:
      disable: true

  cron:
    extends:
      service: api
    command: cron
    healthcheck:
      disable: true
