[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "abrechnung"
authors = [
    { name = "Michael Loipführer", email = "milo@sft.lol" },
    { name = "Jonas Jelten", email = "jj@sft.lol" },
    { name = "Michael Enßlin", email = "mic@sft.lol" }
]
license = { file = "LICENSE" }
dynamic = ["version", "readme"]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 5 - Production/Stable",
]
requires-python = ">=3.10"
dependencies = [
    "typer~=0.9.0",
    "fastapi~=0.103",
    "pydantic[email]~=2.4",
    "uvicorn[standard]~=0.22",
    "python-jose[cryptography]~=3.3",
    "asyncpg~=0.28",
    "passlib[bcrypt]~=1.7",
    "websockets~=10.4",
    "python-multipart~=0.0.6",
    "PyYAML~=6.0",
]

[project.optional-dependencies]
test = [
    "aiosmtpd~=1.4",
    "pytest",
    "pytest-cov",
    "httpx~=0.23",
]
dev = [
    "isort",
    "black",
    "mypy~=1.5",
    "types-PyYAML~=6.0",
    "pylint~=3.0",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-autodoc-typehints",
]

[project.urls]
Source = "https://github.com/SFTtech/abrechung"
Documentation = "https://abrechnung.readthedocs.io"

[project.scripts]
abrechnung = "abrechnung.cli.main:main"

[tool.setuptools.packages.find]
namespaces = false
exclude = ["tests*"]

[tool.setuptools.dynamic]
version = {attr = "abrechnung.__version__"}
readme = {file = ["README.md"]}

[tool.pylint.MASTER]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "fixme",
    "logging-fstring-interpolation",
    "broad-exception-caught"
]

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
pretty = true
plugins = [
    "pydantic.mypy"
]

[tool.coverage.run]
source = [
    "abrechnung"
]