[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "abrechnung"
authors = [
    { name = "Michael Loipführer", email = "milo@sft.lol" },
    { name = "Jonas Jelten", email = "jj@sft.lol" },
    { name = "Michael Enßlin", email = "mic@sft.lol" }
]
license = { file = "LICENSE" }
dynamic = ["version", "description"]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 5 - Production/Stable",
]
requires-python = ">=3.9"
dependencies = [
    "fastapi~=0.102",
    "pydantic[email]~=2.3.0",
    "uvicorn[standard]~=0.20",
    "python-jose[cryptography]~=3.3",
    "asyncpg~=0.27",
    "passlib[bcrypt]~=1.7",
    "websockets~=10.4",
    "python-multipart~=0.0.5",
    "PyYAML~=6.0",
    "schema~=0.7",
]

[project.optional-dependencies]
test = [
    "aiosmtpd~=1.4",
    "pytest",
    "pytest-cov",
    "httpx~=0.23",
]
dev = [
    "black",
    "mypy~=0.991",
    "types-PyYAML~=6.0",
    "pylint~=2.15",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-autodoc-typehints",
]

[project.urls]
Source = "https://github.com/SFTtech/abrechung"
Documentation = "https://abrechnung.readthedocs.io"

[project.scripts]
abrechnung = "abrechnung.__main__:main"

[tool.flit.sdist]
exclude = [
    "frontend/",
    "tools/",
    ".github",
    ".readthedocs.yaml",
    "config",
    "systemd",
]

[tool.pylint.MASTER]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "fixme",
    "logging-fstring-interpolation"
]

[tool.mypy]
ignore_missing_imports = true
pretty = true

[tool.coverage.run]
source = [
    "abrechnung"
]