name: Pull Request
on:
  pull_request:

jobs:
  build_and_test_frontend:
    uses: ./.github/workflows/frontend.yaml
    secrets: inherit

  build_and_test_backend:
    uses: ./.github/workflows/backend.yaml
    secrets: inherit
